spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
  
  mail:
    default-encoding: UTF-8
    protocol: smtp
    #host: localhost
    #port: 2525
    host: smtp.gmail.com
    port: 465
    jndi-name: mail/Session
    password: gxxcglkiyaiohaif # Google App password
    username: rakuraku.pet@gmail.com # Google account mail address
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            #enable: false
            enable: true
          socketFactory:
            #port: 2525
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
        debug: true
    test-connection: false